### ISSUE TITLE
Error occurred while enabling CompassEx v3.0.1

### ISSUE THREAD

**Issue by liquidox** [Philipp15b/CompassEx#21]
2013-06-29 16:00:14 [INFO] [CompassEx] Loading CompassEx v3.0.1
2013-06-29 16:00:24 [INFO] [CompassEx] Enabling CompassEx v3.0.1
2013-06-29 16:00:24 [SEVERE] Error occurred while enabling CompassEx v3.0.1 (Is it up to date?)
        at de.philworld.bukkit.compassex.CompassExCommandExecutor.<init>(CompassExCommandExecutor.java:27)
        at de.philworld.bukkit.compassex.CompassEx.onEnable(CompassEx.java:48)

**Comment by Philipp15b** [comment]
This is not the complete error message. Please post it completely.

**Comment by liquidox** [comment]
16:05:46 [INFO] [CompassEx] Enabling CompassEx v3.0.1
16:05:46 [SEVERE] Error occurred while enabling CompassEx v3.0.1 (Is it up to date?)
java.lang.NullPointerException
        at de.philworld.bukkit.compassex.CompassExCommandExecutor.<init>(CompassExCommandExecutor.java:27)
        at de.philworld.bukkit.compassex.CompassEx.onEnable(CompassEx.java:48)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:382)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:284)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:266)
        at net.minecraft.server.v1_5_R3.MinecraftServer.j(MinecraftServer.java:310)
        at net.minecraft.server.v1_5_R3.MinecraftServer.e(MinecraftServer.java:289)
        at net.minecraft.server.v1_5_R3.MinecraftServer.a(MinecraftServer.java:249)
        at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:158)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by Philipp15b** [comment]
Thanks. This error was reported before and happens due to Bukkit's sub-optimal way of handling conflicts with commands, that means another plugin that started before CompassEx already registered a `/compass` command. I'll create a workaround for this.

**Comment by Philipp15b** [comment]
CompassEx 3.0.2 will be available soon on BukkitDev.
