### ISSUE TITLE
Exception "Specified class does not exist ('de.philworld.bukkit.compassex.util.BlockLocation')"

### ISSUE THREAD

**Issue by Earl-Brown** [Philipp15b/CompassEx#26]
I don't know what information you will need to review/repair this - please let me know, and I'll get it to you as soon as I can.

The error does not seem to impact my server - just ugly messages when loading.

Thanks!

**Comment by bigpresh** [comment]
Hilariously old issue, but commenting anyway because it came up in a search when I had this same problem, so this might help someone after me who faces the same problem...

I was seeing CompassEx fail to load, involving the same error as noted in this ticket:

```

[22:18:08] [Server thread/INFO]: [CompassEx] Enabling CompassEx v3.1.0*
[22:18:08] [Server thread/ERROR]: Error occurred while enabling CompassEx v3.1.0 (Is it up to date?)
org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:50) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
<snip>
        at de.philworld.bukkit.compassex.DeathpointComponent.load(DeathpointComponent.java:42) ~[CompassEx-3.1.0.jar:?]
        at de.philworld.bukkit.compassex.DeathpointComponent.<init>(DeathpointComponent.java:35) ~[CompassEx-3.1.0.jar:?]
        at de.philworld.bukkit.compassex.CompassEx.onEnable(CompassEx.java:43) ~[CompassEx-3.1.0.jar:?]
<snip>
Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('de.philworld.bukkit.compassex.util.BlockLocation')
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:48) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
 ```


I tracked it down to the deathpoints.db.yml file, which referred to the ...BlockLocation class (player name removed for privacy):

```
[davidp@headshrinker:~]$ cat The-Wild/plugins/CompassEx/deathpoints.db.yml
Player_Name_Removed_From_Here:
  ==: de.philworld.bukkit.compassex.util.BlockLocation
  world: world
  x: 200093
  y: 65
  z: -159502

```

On removing the deathpoints.db.yml file and restarting the server, CompassEx was working again.

**Comment by bigpresh** [comment]
Interestingly, as the plugin was disabled another error occurred - but I *suspect* this error is just a symptom of it not having loaded correctly.

```
[22:18:08] [Server thread/INFO]: [CompassEx] Disabling CompassEx v3.1.0
[22:18:08] [Server thread/ERROR]: Error occurred while disabling CompassEx v3.1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.philworld.bukkit.compassex.persistence.PersisterTask.run()" because "this.persister" is null
        at de.philworld.bukkit.compassex.CompassEx.onDisable(CompassEx.java:81) ~[CompassEx-3.1.0.jar:?]
```

**Comment by bigpresh** [comment]
This issue is the same issue as #25 which was closed but the fix there didn't actually work to solve it.  My fix in PR #28 *does* fix it, at least for me.
