### ISSUE TITLE
NullPointerException at startup

### ISSUE THREAD

**Issue by Philipp15b** [Philipp15b/CompassEx#9]
At startup, the following exception is thrown:

2012-04-13 10:25:20 [SEVERE] Error occurred while enabling CompassEx v1.0.0 (Is it up to date?) java.lang.NullPointerException at de.philworld.bukkit.compassex.CompassEx.onEnable(CompassEx.java:101) at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215) at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381) at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250) at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232) at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371) at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358) at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422) at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

https://gist.github.com/2377292

It seems that the plugin command `/compass` is not found, despite the fact that its registered in plugin.yml.

**Comment by dfdgsdfg** [comment]
The command book plugin uses a command /compass .

http://wiki.sk89q.com/wiki/CommandBook/Commands#Player

**Comment by Philipp15b** [comment]
Hmm, I tested it on my local server with WorldEdit and CommandBook 2.1. For some reason no error appears. Both work nicely together...
